import { GraphData, EdgeDef } from "./types";

// Governorate groupings for UI dropdowns
export const GOVERNORATES: Record<string, { label: string; areas: string[] }> = {
  capital: {
    label: "Capital (العاصمة)",
    areas: [
      "Sharq", "Mirqab", "Qibla", "Bneid Al-Gar", "Dasman", "Dasma",
      "Rawdah", "Nuzha", "Shamiyah", "Yarmouk", "Shuwaikh", "Kaifan",
      "Sulaibikhat", "NW Sulaibikhat", "Ghornata", "Abdullah Al-Salem",
      "Doha", "Nahdha", "Daiya", "Watiya", "Salhiya", "Khalidiya",
      "Faiha", "Adailiya", "Mansouriya", "Qortuba", "Sawaber",
      "Qairawan", "South Qairawan",
    ],
  },
  hawalli: {
    label: "Hawalli (حولي)",
    areas: [
      "Salmiya", "Hawally", "Rumaithiya", "Bayan", "Mishref", "Jabriya",
      "Salwa", "Surra", "Qadisiya", "Shuhada", "Hitteen", "Zahra",
      "Shab", "Bida", "Siddiq", "Naqra", "South Surra", "Salam",
    ],
  },
  farwaniya: {
    label: "Farwaniya (الفروانية)",
    areas: [
      "Khaitan", "Rai", "Ferdous", "Abdullah Al-Mubarak",
      "South Abdullah Al-Mubarak", "West Abdullah Al-Mubarak",
      "Sabah Al-Nasser", "Ishbiliyah", "Ardiya", "Andalus",
      "Jleeb Al-Shuyoukh", "Omariya", "Riqqai", "Rehab",
      "Abraq Khaitan", "Abbasiya", "Dhajij",
    ],
  },
  ahmadi: {
    label: "Ahmadi (الأحمدي)",
    areas: [
      "Fahaheel", "Mahboula", "Abu Halifa", "Fintas", "Riqqa", "Mangaf",
      "Sabahiya", "Sabah Al-Ahmad", "East Sabah Al-Ahmad",
      "South Sabah Al-Ahmad", "Hadiya", "Ali Sabah Al-Salem", "Wafra",
      "Egaila", "Khairan", "Nuwaiseeb", "Zour", "Miqaa",
    ],
  },
  jahra: {
    label: "Jahra (الجهراء)",
    areas: [
      "Naeem", "Oyoun", "Sulaibiya", "Taima", "Wahah", "Qasr",
      "Amghara", "Abdali", "Naseem", "Mutlaa", "Salimi",
      "Saad Al-Abdullah", "Rahiya", "Kabd",
    ],
  },
  mubarak: {
    label: "Mubarak Al-Kabeer (مبارك الكبير)",
    areas: [
      "Sabah Al-Salem", "Abu Fatira", "Fnaitees", "Qurain", "Qusour",
      "Mseela", "Abu Al-Hasaniya", "Adan", "Subhan",
    ],
  },
};

export const nodeLatLngs: Record<string, [number, number]> = {
  // ── Capital ────────────────────────────────────────────
  "Sharq":                     [29.371, 47.983],
  "Mirqab":                    [29.369, 47.972],
  "Qibla":                     [29.367, 47.969],
  "Bneid Al-Gar":              [29.356, 47.963],
  "Dasman":                    [29.381, 47.990],
  "Dasma":                     [29.347, 47.975],
  "Rawdah":                    [29.350, 47.987],
  "Nuzha":                     [29.342, 47.985],
  "Shamiyah":                  [29.365, 47.960],
  "Yarmouk":                   [29.353, 47.945],
  "Shuwaikh":                  [29.364, 47.937],
  "Kaifan":                    [29.345, 47.963],
  "Sulaibikhat":               [29.374, 47.897],
  "NW Sulaibikhat":            [29.385, 47.876],
  "Ghornata":                  [29.339, 47.953],
  "Abdullah Al-Salem":         [29.340, 47.971],
  "Doha":                      [29.357, 47.925],
  "Nahdha":                    [29.337, 47.952],
  "Daiya":                     [29.356, 47.952],
  "Watiya":                    [29.360, 47.943],
  "Salhiya":                   [29.371, 47.968],
  "Khalidiya":                 [29.354, 47.963],
  "Faiha":                     [29.348, 47.974],
  "Adailiya":                  [29.354, 47.982],
  "Mansouriya":                [29.346, 47.994],
  "Qortuba":                   [29.330, 47.955],
  "Sawaber":                   [29.370, 47.973],
  "Qairawan":                  [29.322, 47.945],
  "South Qairawan":            [29.313, 47.947],

  // ── Hawalli ────────────────────────────────────────────
  "Salmiya":                   [29.337, 48.071],
  "Hawally":                   [29.333, 47.998],
  "Rumaithiya":                [29.343, 48.087],
  "Bayan":                     [29.297, 48.077],
  "Mishref":                   [29.282, 48.041],
  "Jabriya":                   [29.310, 48.022],
  "Salwa":                     [29.282, 48.075],
  "Surra":                     [29.323, 47.984],
  "Qadisiya":                  [29.321, 47.996],
  "Shuhada":                   [29.328, 47.977],
  "Hitteen":                   [29.320, 47.985],
  "Zahra":                     [29.315, 47.990],
  "Shab":                      [29.337, 48.055],
  "Bida":                      [29.342, 48.062],
  "Siddiq":                    [29.325, 48.001],
  "Naqra":                     [29.316, 48.010],
  "South Surra":               [29.313, 47.979],
  "Salam":                     [29.307, 48.000],

  // ── Farwaniya ──────────────────────────────────────────
  "Khaitan":                   [29.293, 47.962],
  "Rai":                       [29.285, 47.973],
  "Ferdous":                   [29.298, 47.988],
  "Abdullah Al-Mubarak":       [29.339, 47.870],
  "South Abdullah Al-Mubarak": [29.325, 47.867],
  "West Abdullah Al-Mubarak":  [29.330, 47.853],
  "Sabah Al-Nasser":           [29.316, 47.943],
  "Ishbiliyah":                [29.308, 47.951],
  "Ardiya":                    [29.306, 47.933],
  "Andalus":                   [29.297, 47.945],
  "Jleeb Al-Shuyoukh":         [29.305, 47.946],
  "Omariya":                   [29.289, 47.960],
  "Riqqai":                    [29.276, 47.956],
  "Rehab":                     [29.266, 47.973],
  "Abraq Khaitan":             [29.274, 47.980],
  "Abbasiya":                  [29.284, 47.931],
  "Dhajij":                    [29.267, 47.951],

  // ── Ahmadi ─────────────────────────────────────────────
  "Fahaheel":                  [29.071, 48.132],
  "Mahboula":                  [29.087, 48.127],
  "Abu Halifa":                [29.108, 48.125],
  "Fintas":                    [29.155, 48.117],
  "Riqqa":                     [29.135, 48.108],
  "Mangaf":                    [29.094, 48.111],
  "Sabahiya":                  [29.112, 48.096],
  "Sabah Al-Ahmad":            [28.985, 48.217],
  "East Sabah Al-Ahmad":       [28.992, 48.247],
  "South Sabah Al-Ahmad":      [28.960, 48.210],
  "Hadiya":                    [29.055, 48.102],
  "Ali Sabah Al-Salem":        [29.158, 48.089],
  "Wafra":                     [28.626, 47.932],
  "Egaila":                    [29.192, 48.073],
  "Khairan":                   [28.920, 48.311],
  "Nuwaiseeb":                 [28.817, 48.336],
  "Zour":                      [29.017, 48.319],
  "Miqaa":                     [28.710, 47.830],

  // ── Jahra ──────────────────────────────────────────────
  "Naeem":                     [29.363, 47.697],
  "Oyoun":                     [29.355, 47.684],
  "Sulaibiya":                 [29.270, 47.802],
  "Taima":                     [29.394, 47.637],
  "Wahah":                     [29.380, 47.660],
  "Qasr":                      [29.346, 47.668],
  "Amghara":                   [29.189, 47.723],
  "Abdali":                    [29.977, 47.717],
  "Naseem":                    [29.364, 47.729],
  "Mutlaa":                    [29.508, 47.745],
  "Salimi":                    [29.325, 47.530],
  "Saad Al-Abdullah":          [29.426, 47.767],
  "Rahiya":                    [29.263, 47.634],
  "Kabd":                      [29.244, 47.742],

  // ── Mubarak Al-Kabeer ──────────────────────────────────
  "Sabah Al-Salem":            [29.247, 48.059],
  "Abu Fatira":                [29.218, 48.076],
  "Fnaitees":                  [29.234, 48.087],
  "Qurain":                    [29.216, 48.057],
  "Qusour":                    [29.233, 48.048],
  "Mseela":                    [29.196, 48.084],
  "Abu Al-Hasaniya":           [29.261, 48.085],
  "Adan":                      [29.173, 48.082],
  "Subhan":                    [29.225, 48.024],
};

export const kuwaitGraph: GraphData = {
  nodes: Object.keys(nodeLatLngs).map((id) => ({ id })),
  edges: [
    // ── Capital internal ─────────────────────────────────
    { u: "Dasman",                    v: "Sharq",                    weight: 2 },
    { u: "Sharq",                     v: "Salhiya",                  weight: 1 },
    { u: "Sharq",                     v: "Mirqab",                   weight: 1 },
    { u: "Salhiya",                   v: "Mirqab",                   weight: 1 },
    { u: "Salhiya",                   v: "Sawaber",                  weight: 1 },
    { u: "Mirqab",                    v: "Sawaber",                  weight: 1 },
    { u: "Mirqab",                    v: "Qibla",                    weight: 1 },
    { u: "Sawaber",                   v: "Qibla",                    weight: 1 },
    { u: "Dasman",                    v: "Bneid Al-Gar",             weight: 3 },
    { u: "Qibla",                     v: "Bneid Al-Gar",             weight: 1 },
    { u: "Qibla",                     v: "Shamiyah",                 weight: 1 },
    { u: "Bneid Al-Gar",              v: "Khalidiya",                weight: 1 },
    { u: "Bneid Al-Gar",              v: "Dasma",                    weight: 1 },
    { u: "Khalidiya",                 v: "Shamiyah",                 weight: 1 },
    { u: "Khalidiya",                 v: "Faiha",                    weight: 1 },
    { u: "Khalidiya",                 v: "Kaifan",                   weight: 1 },
    { u: "Shamiyah",                  v: "Daiya",                    weight: 1 },
    { u: "Shamiyah",                  v: "Yarmouk",                  weight: 1 },
    { u: "Daiya",                     v: "Watiya",                   weight: 1 },
    { u: "Daiya",                     v: "Yarmouk",                  weight: 1 },
    { u: "Watiya",                    v: "Shuwaikh",                 weight: 1 },
    { u: "Watiya",                    v: "Doha",                     weight: 1 },
    { u: "Shuwaikh",                  v: "Yarmouk",                  weight: 1 },
    { u: "Shuwaikh",                  v: "Doha",                     weight: 1 },
    { u: "Shuwaikh",                  v: "Sulaibikhat",              weight: 4 },
    { u: "Sulaibikhat",               v: "NW Sulaibikhat",           weight: 2 },
    { u: "Dasma",                     v: "Rawdah",                   weight: 1 },
    { u: "Dasma",                     v: "Adailiya",                 weight: 1 },
    { u: "Rawdah",                    v: "Faiha",                    weight: 1 },
    { u: "Rawdah",                    v: "Adailiya",                 weight: 1 },
    { u: "Rawdah",                    v: "Nuzha",                    weight: 1 },
    { u: "Faiha",                     v: "Adailiya",                 weight: 1 },
    { u: "Faiha",                     v: "Abdullah Al-Salem",        weight: 1 },
    { u: "Adailiya",                  v: "Mansouriya",               weight: 1 },
    { u: "Kaifan",                    v: "Abdullah Al-Salem",        weight: 1 },
    { u: "Kaifan",                    v: "Ghornata",                 weight: 1 },
    { u: "Abdullah Al-Salem",         v: "Ghornata",                 weight: 1 },
    { u: "Mansouriya",                v: "Nuzha",                    weight: 1 },
    { u: "Nuzha",                     v: "Rawdah",                   weight: 1 },
    { u: "Yarmouk",                   v: "Qortuba",                  weight: 2 },
    { u: "Doha",                      v: "Nahdha",                   weight: 1 },
    { u: "Nahdha",                    v: "Qortuba",                  weight: 1 },
    { u: "Qortuba",                   v: "Ghornata",                 weight: 1 },
    { u: "Ghornata",                  v: "Qairawan",                 weight: 1 },
    { u: "Qairawan",                  v: "South Qairawan",           weight: 1 },

    // ── Capital ↔ other governorates ─────────────────────
    { u: "NW Sulaibikhat",            v: "Abdullah Al-Mubarak",      weight: 3 },
    { u: "Shuwaikh",                  v: "Abdullah Al-Mubarak",      weight: 7 },
    { u: "South Qairawan",            v: "Sabah Al-Nasser",          weight: 1 },
    { u: "Yarmouk",                   v: "Sabah Al-Nasser",          weight: 2 },
    { u: "Ghornata",                  v: "Ishbiliyah",               weight: 1 },
    { u: "Mansouriya",                v: "Hawally",                  weight: 1 },
    { u: "Nuzha",                     v: "Hawally",                  weight: 2 },
    { u: "Abdullah Al-Salem",         v: "Surra",                    weight: 1 },
    { u: "Faiha",                     v: "Surra",                    weight: 1 },
    { u: "Faiha",                     v: "Qadisiya",                 weight: 1 },
    { u: "Adailiya",                  v: "Surra",                    weight: 1 },
    { u: "Naeem",                     v: "Sulaibikhat",              weight: 9 },
    { u: "Naseem",                    v: "Doha",                     weight: 4 },

    // ── Hawalli internal ─────────────────────────────────
    { u: "Surra",                     v: "Qadisiya",                 weight: 1 },
    { u: "Surra",                     v: "Shuhada",                  weight: 1 },
    { u: "Surra",                     v: "South Surra",              weight: 1 },
    { u: "Qadisiya",                  v: "Shuhada",                  weight: 1 },
    { u: "Qadisiya",                  v: "Hawally",                  weight: 1 },
    { u: "Shuhada",                   v: "Hitteen",                  weight: 1 },
    { u: "Hawally",                   v: "Siddiq",                   weight: 1 },
    { u: "Hawally",                   v: "Naqra",                    weight: 1 },
    { u: "Hawally",                   v: "Jabriya",                  weight: 2 },
    { u: "Hitteen",                   v: "Zahra",                    weight: 1 },
    { u: "Zahra",                     v: "Siddiq",                   weight: 1 },
    { u: "Siddiq",                    v: "Naqra",                    weight: 1 },
    { u: "South Surra",               v: "Salam",                    weight: 1 },
    { u: "Naqra",                     v: "Salam",                    weight: 1 },
    { u: "Salam",                     v: "Jabriya",                  weight: 1 },
    { u: "Jabriya",                   v: "Mishref",                  weight: 3 },
    { u: "Salmiya",                   v: "Shab",                     weight: 2 },
    { u: "Salmiya",                   v: "Bida",                     weight: 1 },
    { u: "Salmiya",                   v: "Rumaithiya",               weight: 3 },
    { u: "Shab",                      v: "Bida",                     weight: 1 },
    { u: "Bida",                      v: "Rumaithiya",               weight: 2 },
    { u: "Rumaithiya",                v: "Bayan",                    weight: 4 },
    { u: "Bayan",                     v: "Salwa",                    weight: 1 },
    { u: "Salwa",                     v: "Mishref",                  weight: 4 },
    { u: "Mishref",                   v: "Bayan",                    weight: 3 },

    // ── Hawalli ↔ other governorates ─────────────────────
    { u: "Rumaithiya",                v: "Fnaitees",                 weight: 2 },
    { u: "Bayan",                     v: "Abu Al-Hasaniya",          weight: 2 },
    { u: "Salwa",                     v: "Sabah Al-Salem",           weight: 4 },
    { u: "Mishref",                   v: "Sabah Al-Salem",           weight: 4 },
    { u: "Salmiya",                   v: "Egaila",                   weight: 4 },
    { u: "Salam",                     v: "Khaitan",                  weight: 1 },
    { u: "South Surra",               v: "Khaitan",                  weight: 2 },
    { u: "Zahra",                     v: "Khaitan",                  weight: 2 },
    { u: "Ferdous",                   v: "Salam",                    weight: 2 },

    // ── Farwaniya internal ───────────────────────────────
    { u: "Sabah Al-Nasser",           v: "Ishbiliyah",               weight: 1 },
    { u: "Sabah Al-Nasser",           v: "Ardiya",                   weight: 1 },
    { u: "Ishbiliyah",                v: "Ardiya",                   weight: 1 },
    { u: "Ishbiliyah",                v: "Jleeb Al-Shuyoukh",        weight: 1 },
    { u: "Ardiya",                    v: "Jleeb Al-Shuyoukh",        weight: 1 },
    { u: "Ardiya",                    v: "Abbasiya",                 weight: 1 },
    { u: "Jleeb Al-Shuyoukh",         v: "Andalus",                  weight: 1 },
    { u: "Jleeb Al-Shuyoukh",         v: "Khaitan",                  weight: 1 },
    { u: "Andalus",                   v: "Khaitan",                  weight: 1 },
    { u: "Andalus",                   v: "Omariya",                  weight: 1 },
    { u: "Khaitan",                   v: "Omariya",                  weight: 1 },
    { u: "Khaitan",                   v: "Rai",                      weight: 1 },
    { u: "Omariya",                   v: "Riqqai",                   weight: 2 },
    { u: "Rai",                       v: "Ferdous",                  weight: 1 },
    { u: "Rai",                       v: "Riqqai",                   weight: 1 },
    { u: "Riqqai",                    v: "Dhajij",                   weight: 1 },
    { u: "Riqqai",                    v: "Abraq Khaitan",            weight: 1 },
    { u: "Abraq Khaitan",             v: "Rehab",                    weight: 1 },
    { u: "Dhajij",                    v: "Rehab",                    weight: 1 },
    { u: "Abdullah Al-Mubarak",       v: "West Abdullah Al-Mubarak", weight: 2 },
    { u: "Abdullah Al-Mubarak",       v: "South Abdullah Al-Mubarak",weight: 2 },
    { u: "West Abdullah Al-Mubarak",  v: "South Abdullah Al-Mubarak",weight: 1 },
    { u: "South Abdullah Al-Mubarak", v: "Sabah Al-Nasser",          weight: 2 },

    // ── Farwaniya ↔ other governorates ───────────────────
    { u: "Abbasiya",                  v: "Sulaibiya",                weight: 8 },
    { u: "Rehab",                     v: "Subhan",                   weight: 5 },
    { u: "Abraq Khaitan",             v: "Subhan",                   weight: 5 },

    // ── Ahmadi internal ──────────────────────────────────
    { u: "Egaila",                    v: "Ali Sabah Al-Salem",       weight: 4 },
    { u: "Ali Sabah Al-Salem",        v: "Riqqa",                    weight: 2 },
    { u: "Ali Sabah Al-Salem",        v: "Fintas",                   weight: 1 },
    { u: "Fintas",                    v: "Riqqa",                    weight: 2 },
    { u: "Riqqa",                     v: "Sabahiya",                 weight: 2 },
    { u: "Sabahiya",                  v: "Abu Halifa",               weight: 1 },
    { u: "Abu Halifa",                v: "Mangaf",                   weight: 2 },
    { u: "Abu Halifa",                v: "Mahboula",                 weight: 2 },
    { u: "Mangaf",                    v: "Mahboula",                 weight: 1 },
    { u: "Mangaf",                    v: "Fahaheel",                 weight: 2 },
    { u: "Mahboula",                  v: "Fahaheel",                 weight: 1 },
    { u: "Fahaheel",                  v: "Hadiya",                   weight: 2 },
    { u: "Hadiya",                    v: "Sabah Al-Ahmad",           weight: 13 },
    { u: "Sabah Al-Ahmad",            v: "East Sabah Al-Ahmad",      weight: 3 },
    { u: "Sabah Al-Ahmad",            v: "South Sabah Al-Ahmad",     weight: 4 },
    { u: "East Sabah Al-Ahmad",       v: "South Sabah Al-Ahmad",     weight: 4 },
    { u: "East Sabah Al-Ahmad",       v: "Zour",                     weight: 9 },
    { u: "East Sabah Al-Ahmad",       v: "Khairan",                  weight: 12 },
    { u: "Khairan",                   v: "Nuwaiseeb",                weight: 12 },
    { u: "Nuwaiseeb",                 v: "Zour",                     weight: 14 },
    { u: "South Sabah Al-Ahmad",      v: "Wafra",                    weight: 40 },
    { u: "Wafra",                     v: "Miqaa",                    weight: 13 },

    // ── Ahmadi ↔ other governorates ──────────────────────
    { u: "Egaila",                    v: "Sabah Al-Salem",           weight: 6 },
    { u: "Egaila",                    v: "Adan",                     weight: 2 },
    { u: "Fintas",                    v: "Adan",                     weight: 3 },
    { u: "Fintas",                    v: "Mseela",                   weight: 4 },
    { u: "Sabahiya",                  v: "Mseela",                   weight: 3 },

    // ── Jahra internal ───────────────────────────────────
    { u: "Naeem",                     v: "Oyoun",                    weight: 2 },
    { u: "Naeem",                     v: "Naseem",                   weight: 6 },
    { u: "Naeem",                     v: "Qasr",                     weight: 4 },
    { u: "Oyoun",                     v: "Wahah",                    weight: 3 },
    { u: "Oyoun",                     v: "Qasr",                     weight: 4 },
    { u: "Wahah",                     v: "Taima",                    weight: 3 },
    { u: "Taima",                     v: "Naseem",                   weight: 6 },
    { u: "Qasr",                      v: "Rahiya",                   weight: 5 },
    { u: "Naseem",                    v: "Saad Al-Abdullah",         weight: 7 },
    { u: "Naseem",                    v: "Mutlaa",                   weight: 16 },
    { u: "Saad Al-Abdullah",          v: "Mutlaa",                   weight: 10 },
    { u: "Mutlaa",                    v: "Abdali",                   weight: 52 },
    { u: "Rahiya",                    v: "Amghara",                  weight: 8 },
    { u: "Amghara",                   v: "Kabd",                     weight: 6 },
    { u: "Kabd",                      v: "Sulaibiya",                weight: 5 },
    { u: "Sulaibiya",                 v: "Rahiya",                   weight: 7 },
    { u: "Salimi",                    v: "Rahiya",                   weight: 10 },
    { u: "Salimi",                    v: "Taima",                    weight: 11 },

    // ── Jahra ↔ other governorates ───────────────────────
    { u: "Sulaibiya",                 v: "Abbasiya",                 weight: 8 },
    { u: "Amghara",                   v: "Sulaibiya",                weight: 9 },

    // ── Mubarak Al-Kabeer internal ───────────────────────
    { u: "Sabah Al-Salem",            v: "Abu Al-Hasaniya",          weight: 2 },
    { u: "Sabah Al-Salem",            v: "Qurain",                   weight: 2 },
    { u: "Sabah Al-Salem",            v: "Fnaitees",                 weight: 2 },
    { u: "Sabah Al-Salem",            v: "Qusour",                   weight: 2 },
    { u: "Abu Al-Hasaniya",           v: "Fnaitees",                 weight: 2 },
    { u: "Qurain",                    v: "Qusour",                   weight: 2 },
    { u: "Qurain",                    v: "Abu Fatira",               weight: 1 },
    { u: "Qusour",                    v: "Subhan",                   weight: 3 },
    { u: "Fnaitees",                  v: "Mseela",                   weight: 2 },
    { u: "Mseela",                    v: "Abu Fatira",               weight: 3 },
    { u: "Mseela",                    v: "Adan",                     weight: 3 },
    { u: "Adan",                      v: "Abu Fatira",               weight: 3 },
    { u: "Subhan",                    v: "Adan",                     weight: 4 },

    // ── Mubarak Al-Kabeer ↔ other governorates ────────────
    { u: "Abu Al-Hasaniya",           v: "Bayan",                    weight: 2 },
    { u: "Fnaitees",                  v: "Rumaithiya",               weight: 2 },
    { u: "Subhan",                    v: "Rehab",                    weight: 5 },
  ],
};

export function getNeighbors(
  nodeId: string,
  edges: EdgeDef[]
): Array<{ dest: string; weight: number }> {
  const result: Array<{ dest: string; weight: number }> = [];
  for (const e of edges) {
    if (e.u === nodeId) result.push({ dest: e.v, weight: e.weight });
    else if (e.v === nodeId) result.push({ dest: e.u, weight: e.weight });
  }
  return result;
}
