import { GraphData, EdgeDef } from "./types";

// Governorate groupings for UI dropdowns
export const GOVERNORATES: Record<string, { label: string; areas: string[] }> = {
  capital: {
    label: "Capital (العاصمة)",
    areas: [
      "Sharq", "Mirqab", "Qibla", "Bneid Al-Gar", "Dasman", "Dasma",
      "Rawdah", "Nuzha", "Shamiyah", "Yarmouk", "Shuwaikh", "Kaifan",
      "Sulaibikhat", "NW Sulaibikhat", "Ghornata", "Abdullah Al-Salem",
      "Doha", "Nahdha", "Daiya", "Watiya", "Salhiya", "Khalidiya",
      "Faiha", "Adailiya", "Mansouriya", "Qortuba", "Sawaber",
      "Qairawan", "South Qairawan",
    ],
  },
  hawalli: {
    label: "Hawalli (حولي)",
    areas: [
      "Salmiya", "Hawally", "Rumaithiya", "Bayan", "Mishref", "Jabriya",
      "Salwa", "Surra", "Qadisiya", "Shuhada", "Hitteen", "Zahra",
      "Shab", "Bida", "Siddiq", "Naqra", "South Surra", "Salam",
    ],
  },
  farwaniya: {
    label: "Farwaniya (الفروانية)",
    areas: [
      "Khaitan", "Rai", "Ferdous", "Abdullah Al-Mubarak",
      "South Abdullah Al-Mubarak", "West Abdullah Al-Mubarak",
      "Sabah Al-Nasser", "Ishbiliyah", "Ardiya", "Andalus",
      "Jleeb Al-Shuyoukh", "Omariya", "Riqqai", "Rehab",
      "Abraq Khaitan", "Abbasiya", "Dhajij",
    ],
  },
  ahmadi: {
    label: "Ahmadi (الأحمدي)",
    areas: [
      "Fahaheel", "Mahboula", "Abu Halifa", "Fintas", "Riqqa", "Mangaf",
      "Sabahiya", "Sabah Al-Ahmad", "East Sabah Al-Ahmad",
      "South Sabah Al-Ahmad", "Hadiya", "Ali Sabah Al-Salem", "Wafra",
      "Egaila", "Khairan", "Nuwaiseeb", "Zour", "Miqaa",
    ],
  },
  jahra: {
    label: "Jahra (الجهراء)",
    areas: [
      "Naeem", "Oyoun", "Sulaibiya", "Taima", "Wahah", "Qasr",
      "Amghara", "Abdali", "Naseem", "Mutlaa", "Salimi",
      "Saad Al-Abdullah", "Rahiya", "Kabd",
    ],
  },
  mubarak: {
    label: "Mubarak Al-Kabeer (مبارك الكبير)",
    areas: [
      "Sabah Al-Salem", "Abu Fatira", "Fnaitees", "Qurain", "Qusour",
      "Mseela", "Abu Al-Hasaniya", "Adan", "Subhan",
    ],
  },
};

export const nodeLatLngs: Record<string, [number, number]> = {
  // ── Capital (العاصمة) ──────────────────────────────────
  "Sharq":                     [29.3805, 47.9831],
  "Mirqab":                    [29.3661, 47.9837],
  "Qibla":                     [29.3699, 47.9688],
  "Salhiya":                   [29.3635, 47.9676],
  "Sawaber":                   [29.3764, 47.9825],
  "Dasman":                    [29.3878, 47.9998],
  "Bneid Al-Gar":              [29.3557, 47.9626],
  "Dasma":                     [29.3664, 48.0007],
  "Rawdah":                    [29.3290, 47.9986],
  "Nuzha":                     [29.3441, 47.9844],
  "Shamiyah":                  [29.3509, 47.9688],
  "Yarmouk":                   [29.3128, 47.9688],
  "Shuwaikh":                  [29.3472, 47.9160],
  "Kaifan":                    [29.3389, 47.9618],
  "Sulaibikhat":               [29.3156, 47.8403],
  "NW Sulaibikhat":            [29.3278, 47.8105],
  "Ghornata":                  [29.3268, 47.9532],
  "Abdullah Al-Salem":         [29.3519, 47.9837],
  "Doha":                      [29.3573, 47.9255],
  "Nahdha":                    [29.3285, 47.9522],
  "Daiya":                     [29.3493, 47.9525],
  "Watiya":                    [29.3622, 47.9629],
  "Khalidiya":                 [29.3286, 47.9583],
  "Faiha":                     [29.3404, 47.9787],
  "Adailiya":                  [29.3281, 47.9837],
  "Mansouriya":                [29.3573, 47.9948],
  "Qortuba":                   [29.3123, 47.9862],
  "Qairawan":                  [29.3148, 47.9462],
  "South Qairawan":            [29.3058, 47.9472],

  // ── Hawalli (حولي) ─────────────────────────────────────
  "Salmiya":                   [29.3407, 48.0839],
  "Hawally":                   [29.3378, 48.0235],
  "Rumaithiya":                [29.3161, 48.0720],
  "Bayan":                     [29.2980, 48.0511],
  "Mishref":                   [29.2781, 48.0671],
  "Jabriya":                   [29.3198, 48.0257],
  "Salwa":                     [29.2958, 48.0767],
  "Surra":                     [29.3131, 48.0058],
  "Qadisiya":                  [29.3213, 47.9968],
  "Shuhada":                   [29.2709, 48.0332],
  "Hitteen":                   [29.2842, 48.0184],
  "Zahra":                     [29.2719, 48.0020],
  "Shab":                      [29.3373, 48.0553],
  "Bida":                      [29.3194, 48.0899],
  "Siddiq":                    [29.3253, 48.0012],
  "Naqra":                     [29.3162, 48.0122],
  "South Surra":               [29.3138, 48.0084],
  "Salam":                     [29.2994, 48.0132],

  // ── Farwaniya (الفروانية) ──────────────────────────────
  "Khaitan":                   [29.2839, 47.9751],
  "Rai":                       [29.2815, 47.9606],
  "Ferdous":                   [29.2900, 47.9750],
  "Abdullah Al-Mubarak":       [29.2429, 47.9018],
  "South Abdullah Al-Mubarak": [29.2107, 47.9032],
  "West Abdullah Al-Mubarak":  [29.2451, 47.8695],
  "Sabah Al-Nasser":           [29.2707, 47.8831],
  "Ishbiliyah":                [29.2734, 47.9435],
  "Ardiya":                    [29.2888, 47.9059],
  "Andalus":                   [29.3042, 47.8847],
  "Jleeb Al-Shuyoukh":         [29.2596, 47.9331],
  "Omariya":                   [29.2958, 47.9557],
  "Riqqai":                    [29.2758, 47.9568],
  "Rehab":                     [29.2852, 47.9342],
  "Abraq Khaitan":             [29.2742, 47.9802],
  "Abbasiya":                  [29.2563, 47.9351],
  "Dhajij":                    [29.2620, 47.9630],

  // ── Ahmadi (الأحمدي) ───────────────────────────────────
  "Egaila":                    [29.1687, 48.1009],
  "Ali Sabah Al-Salem":        [29.1583, 48.0888],
  "Fintas":                    [29.1705, 48.1193],
  "Riqqa":                     [29.1504, 48.1051],
  "Sabahiya":                  [29.1081, 48.1059],
  "Abu Halifa":                [29.1282, 48.1259],
  "Mangaf":                    [29.1073, 48.1240],
  "Mahboula":                  [29.1490, 48.1197],
  "Fahaheel":                  [29.0830, 48.1332],
  "Hadiya":                    [29.1459, 48.0928],
  "Sabah Al-Ahmad":            [29.0222, 48.0853],
  "East Sabah Al-Ahmad":       [29.0273, 48.1153],
  "South Sabah Al-Ahmad":      [28.9882, 48.0832],
  "Zour":                      [28.7117, 48.3290],
  "Khairan":                   [28.6624, 48.3881],
  "Nuwaiseeb":                 [28.5642, 48.4041],
  "Wafra":                     [28.6243, 47.9318],
  "Miqaa":                     [28.7098, 47.8328],

  // ── Jahra (الجهراء) ────────────────────────────────────
  "Naeem":                     [29.3335, 47.6935],
  "Oyoun":                     [29.3303, 47.6578],
  "Sulaibiya":                 [29.2839, 47.8252],
  "Taima":                     [29.3289, 47.6816],
  "Wahah":                     [29.3445, 47.6578],
  "Qasr":                      [29.3420, 47.6960],
  "Amghara":                   [29.3069, 47.7508],
  "Abdali":                    [29.9847, 47.7297],
  "Naseem":                    [29.3208, 47.6790],
  "Mutlaa":                    [29.4624, 47.5905],
  "Salimi":                    [29.3247, 47.5303],
  "Saad Al-Abdullah":          [29.3139, 47.7194],
  "Rahiya":                    [29.3368, 47.6752],
  "Kabd":                      [29.0984, 47.7221],

  // ── Mubarak Al-Kabeer (مبارك الكبير) ───────────────────
  "Abu Al-Hasaniya":           [29.1909, 48.1139],
  "Sabah Al-Salem":            [29.2566, 48.0626],
  "Fnaitees":                  [29.2208, 48.0952],
  "Qurain":                    [29.2013, 48.0786],
  "Qusour":                    [29.2328, 48.0478],
  "Subhan":                    [29.2264, 48.0144],
  "Mseela":                    [29.1887, 48.0807],
  "Abu Fatira":                [29.1976, 48.1034],
  "Adan":                      [29.2336, 48.0679],
};

export const kuwaitGraph: GraphData = {
  nodes: Object.keys(nodeLatLngs).map((id) => ({ id })),
  edges: [
    // ── Capital internal ─────────────────────────────────
    { u: "Dasman",                    v: "Sharq",                    weight: 2 },
    { u: "Sharq",                     v: "Salhiya",                  weight: 1 },
    { u: "Sharq",                     v: "Mirqab",                   weight: 1 },
    { u: "Salhiya",                   v: "Mirqab",                   weight: 1 },
    { u: "Salhiya",                   v: "Sawaber",                  weight: 1 },
    { u: "Mirqab",                    v: "Sawaber",                  weight: 1 },
    { u: "Mirqab",                    v: "Qibla",                    weight: 1 },
    { u: "Sawaber",                   v: "Qibla",                    weight: 1 },
    { u: "Dasman",                    v: "Bneid Al-Gar",             weight: 3 },
    { u: "Qibla",                     v: "Bneid Al-Gar",             weight: 1 },
    { u: "Qibla",                     v: "Shamiyah",                 weight: 1 },
    { u: "Bneid Al-Gar",              v: "Khalidiya",                weight: 1 },
    { u: "Bneid Al-Gar",              v: "Dasma",                    weight: 1 },
    { u: "Khalidiya",                 v: "Shamiyah",                 weight: 1 },
    { u: "Khalidiya",                 v: "Faiha",                    weight: 1 },
    { u: "Khalidiya",                 v: "Kaifan",                   weight: 1 },
    { u: "Shamiyah",                  v: "Daiya",                    weight: 1 },
    { u: "Shamiyah",                  v: "Yarmouk",                  weight: 1 },
    { u: "Daiya",                     v: "Watiya",                   weight: 1 },
    { u: "Daiya",                     v: "Yarmouk",                  weight: 1 },
    { u: "Watiya",                    v: "Shuwaikh",                 weight: 1 },
    { u: "Watiya",                    v: "Doha",                     weight: 1 },
    { u: "Shuwaikh",                  v: "Yarmouk",                  weight: 1 },
    { u: "Shuwaikh",                  v: "Doha",                     weight: 1 },
    { u: "Shuwaikh",                  v: "Sulaibikhat",              weight: 4 },
    { u: "Sulaibikhat",               v: "NW Sulaibikhat",           weight: 2 },
    { u: "Dasma",                     v: "Rawdah",                   weight: 1 },
    { u: "Dasma",                     v: "Adailiya",                 weight: 1 },
    { u: "Rawdah",                    v: "Faiha",                    weight: 1 },
    { u: "Rawdah",                    v: "Adailiya",                 weight: 1 },
    { u: "Rawdah",                    v: "Nuzha",                    weight: 1 },
    { u: "Faiha",                     v: "Adailiya",                 weight: 1 },
    { u: "Faiha",                     v: "Abdullah Al-Salem",        weight: 1 },
    { u: "Adailiya",                  v: "Mansouriya",               weight: 1 },
    { u: "Kaifan",                    v: "Abdullah Al-Salem",        weight: 1 },
    { u: "Kaifan",                    v: "Ghornata",                 weight: 1 },
    { u: "Abdullah Al-Salem",         v: "Ghornata",                 weight: 1 },
    { u: "Mansouriya",                v: "Nuzha",                    weight: 1 },
    { u: "Nuzha",                     v: "Rawdah",                   weight: 1 },
    { u: "Yarmouk",                   v: "Qortuba",                  weight: 2 },
    { u: "Doha",                      v: "Nahdha",                   weight: 1 },
    { u: "Nahdha",                    v: "Qortuba",                  weight: 1 },
    { u: "Qortuba",                   v: "Ghornata",                 weight: 1 },
    { u: "Ghornata",                  v: "Qairawan",                 weight: 1 },
    { u: "Qairawan",                  v: "South Qairawan",           weight: 1 },

    // ── Capital ↔ other governorates ─────────────────────
    { u: "NW Sulaibikhat",            v: "Abdullah Al-Mubarak",      weight: 3 },
    { u: "Shuwaikh",                  v: "Abdullah Al-Mubarak",      weight: 7 },
    { u: "South Qairawan",            v: "Sabah Al-Nasser",          weight: 1 },
    { u: "Yarmouk",                   v: "Sabah Al-Nasser",          weight: 2 },
    { u: "Ghornata",                  v: "Ishbiliyah",               weight: 1 },
    { u: "Mansouriya",                v: "Hawally",                  weight: 1 },
    { u: "Nuzha",                     v: "Hawally",                  weight: 2 },
    { u: "Abdullah Al-Salem",         v: "Surra",                    weight: 1 },
    { u: "Faiha",                     v: "Surra",                    weight: 1 },
    { u: "Faiha",                     v: "Qadisiya",                 weight: 1 },
    { u: "Adailiya",                  v: "Surra",                    weight: 1 },
    { u: "Naeem",                     v: "Sulaibikhat",              weight: 9 },
    { u: "Naseem",                    v: "Doha",                     weight: 4 },

    // ── Hawalli internal ─────────────────────────────────
    { u: "Surra",                     v: "Qadisiya",                 weight: 1 },
    { u: "Surra",                     v: "Shuhada",                  weight: 1 },
    { u: "Surra",                     v: "South Surra",              weight: 1 },
    { u: "Qadisiya",                  v: "Shuhada",                  weight: 1 },
    { u: "Qadisiya",                  v: "Hawally",                  weight: 1 },
    { u: "Shuhada",                   v: "Hitteen",                  weight: 1 },
    { u: "Hawally",                   v: "Siddiq",                   weight: 1 },
    { u: "Hawally",                   v: "Naqra",                    weight: 1 },
    { u: "Hawally",                   v: "Jabriya",                  weight: 2 },
    { u: "Hitteen",                   v: "Zahra",                    weight: 1 },
    { u: "Zahra",                     v: "Siddiq",                   weight: 1 },
    { u: "Siddiq",                    v: "Naqra",                    weight: 1 },
    { u: "South Surra",               v: "Salam",                    weight: 1 },
    { u: "Naqra",                     v: "Salam",                    weight: 1 },
    { u: "Salam",                     v: "Jabriya",                  weight: 1 },
    { u: "Jabriya",                   v: "Mishref",                  weight: 3 },
    { u: "Salmiya",                   v: "Shab",                     weight: 2 },
    { u: "Salmiya",                   v: "Bida",                     weight: 1 },
    { u: "Salmiya",                   v: "Rumaithiya",               weight: 3 },
    { u: "Shab",                      v: "Bida",                     weight: 1 },
    { u: "Bida",                      v: "Rumaithiya",               weight: 2 },
    { u: "Rumaithiya",                v: "Bayan",                    weight: 4 },
    { u: "Bayan",                     v: "Salwa",                    weight: 1 },
    { u: "Salwa",                     v: "Mishref",                  weight: 4 },
    { u: "Mishref",                   v: "Bayan",                    weight: 3 },

    // ── Hawalli ↔ other governorates ─────────────────────
    { u: "Rumaithiya",                v: "Fnaitees",                 weight: 2 },
    { u: "Bayan",                     v: "Abu Al-Hasaniya",          weight: 2 },
    { u: "Salwa",                     v: "Sabah Al-Salem",           weight: 4 },
    { u: "Mishref",                   v: "Sabah Al-Salem",           weight: 4 },
    { u: "Salmiya",                   v: "Egaila",                   weight: 4 },
    { u: "Salam",                     v: "Khaitan",                  weight: 1 },
    { u: "South Surra",               v: "Khaitan",                  weight: 2 },
    { u: "Zahra",                     v: "Khaitan",                  weight: 2 },
    { u: "Ferdous",                   v: "Salam",                    weight: 2 },

    // ── Farwaniya internal ───────────────────────────────
    { u: "Sabah Al-Nasser",           v: "Ishbiliyah",               weight: 1 },
    { u: "Sabah Al-Nasser",           v: "Ardiya",                   weight: 1 },
    { u: "Ishbiliyah",                v: "Ardiya",                   weight: 1 },
    { u: "Ishbiliyah",                v: "Jleeb Al-Shuyoukh",        weight: 1 },
    { u: "Ardiya",                    v: "Jleeb Al-Shuyoukh",        weight: 1 },
    { u: "Ardiya",                    v: "Abbasiya",                 weight: 1 },
    { u: "Jleeb Al-Shuyoukh",         v: "Andalus",                  weight: 1 },
    { u: "Jleeb Al-Shuyoukh",         v: "Khaitan",                  weight: 1 },
    { u: "Andalus",                   v: "Khaitan",                  weight: 1 },
    { u: "Andalus",                   v: "Omariya",                  weight: 1 },
    { u: "Khaitan",                   v: "Omariya",                  weight: 1 },
    { u: "Khaitan",                   v: "Rai",                      weight: 1 },
    { u: "Omariya",                   v: "Riqqai",                   weight: 2 },
    { u: "Rai",                       v: "Ferdous",                  weight: 1 },
    { u: "Rai",                       v: "Riqqai",                   weight: 1 },
    { u: "Riqqai",                    v: "Dhajij",                   weight: 1 },
    { u: "Riqqai",                    v: "Abraq Khaitan",            weight: 1 },
    { u: "Abraq Khaitan",             v: "Rehab",                    weight: 1 },
    { u: "Dhajij",                    v: "Rehab",                    weight: 1 },
    { u: "Abdullah Al-Mubarak",       v: "West Abdullah Al-Mubarak", weight: 2 },
    { u: "Abdullah Al-Mubarak",       v: "South Abdullah Al-Mubarak",weight: 2 },
    { u: "West Abdullah Al-Mubarak",  v: "South Abdullah Al-Mubarak",weight: 1 },
    { u: "South Abdullah Al-Mubarak", v: "Sabah Al-Nasser",          weight: 2 },

    // ── Farwaniya ↔ other governorates ───────────────────
    { u: "Abbasiya",                  v: "Sulaibiya",                weight: 8 },
    { u: "Rehab",                     v: "Subhan",                   weight: 5 },
    { u: "Abraq Khaitan",             v: "Subhan",                   weight: 5 },

    // ── Ahmadi internal ──────────────────────────────────
    { u: "Egaila",                    v: "Ali Sabah Al-Salem",       weight: 4 },
    { u: "Ali Sabah Al-Salem",        v: "Riqqa",                    weight: 2 },
    { u: "Ali Sabah Al-Salem",        v: "Fintas",                   weight: 1 },
    { u: "Fintas",                    v: "Riqqa",                    weight: 2 },
    { u: "Riqqa",                     v: "Sabahiya",                 weight: 2 },
    { u: "Sabahiya",                  v: "Abu Halifa",               weight: 1 },
    { u: "Abu Halifa",                v: "Mangaf",                   weight: 2 },
    { u: "Abu Halifa",                v: "Mahboula",                 weight: 2 },
    { u: "Mangaf",                    v: "Mahboula",                 weight: 1 },
    { u: "Mangaf",                    v: "Fahaheel",                 weight: 2 },
    { u: "Mahboula",                  v: "Fahaheel",                 weight: 1 },
    { u: "Fahaheel",                  v: "Hadiya",                   weight: 2 },
    { u: "Hadiya",                    v: "Sabah Al-Ahmad",           weight: 13 },
    { u: "Sabah Al-Ahmad",            v: "East Sabah Al-Ahmad",      weight: 3 },
    { u: "Sabah Al-Ahmad",            v: "South Sabah Al-Ahmad",     weight: 4 },
    { u: "East Sabah Al-Ahmad",       v: "South Sabah Al-Ahmad",     weight: 4 },
    { u: "East Sabah Al-Ahmad",       v: "Zour",                     weight: 9 },
    { u: "East Sabah Al-Ahmad",       v: "Khairan",                  weight: 12 },
    { u: "Khairan",                   v: "Nuwaiseeb",                weight: 12 },
    { u: "Nuwaiseeb",                 v: "Zour",                     weight: 14 },
    { u: "South Sabah Al-Ahmad",      v: "Wafra",                    weight: 40 },
    { u: "Wafra",                     v: "Miqaa",                    weight: 13 },

    // ── Ahmadi ↔ other governorates ──────────────────────
    { u: "Egaila",                    v: "Sabah Al-Salem",           weight: 6 },
    { u: "Egaila",                    v: "Adan",                     weight: 2 },
    { u: "Fintas",                    v: "Adan",                     weight: 3 },
    { u: "Fintas",                    v: "Mseela",                   weight: 4 },
    { u: "Sabahiya",                  v: "Mseela",                   weight: 3 },

    // ── Jahra internal ───────────────────────────────────
    { u: "Naeem",                     v: "Oyoun",                    weight: 2 },
    { u: "Naeem",                     v: "Naseem",                   weight: 6 },
    { u: "Naeem",                     v: "Qasr",                     weight: 4 },
    { u: "Oyoun",                     v: "Wahah",                    weight: 3 },
    { u: "Oyoun",                     v: "Qasr",                     weight: 4 },
    { u: "Wahah",                     v: "Taima",                    weight: 3 },
    { u: "Taima",                     v: "Naseem",                   weight: 6 },
    { u: "Qasr",                      v: "Rahiya",                   weight: 5 },
    { u: "Naseem",                    v: "Saad Al-Abdullah",         weight: 7 },
    { u: "Naseem",                    v: "Mutlaa",                   weight: 16 },
    { u: "Saad Al-Abdullah",          v: "Mutlaa",                   weight: 10 },
    { u: "Mutlaa",                    v: "Abdali",                   weight: 52 },
    { u: "Rahiya",                    v: "Amghara",                  weight: 8 },
    { u: "Amghara",                   v: "Kabd",                     weight: 6 },
    { u: "Kabd",                      v: "Sulaibiya",                weight: 5 },
    { u: "Sulaibiya",                 v: "Rahiya",                   weight: 7 },
    { u: "Salimi",                    v: "Rahiya",                   weight: 10 },
    { u: "Salimi",                    v: "Taima",                    weight: 11 },

    // ── Jahra ↔ other governorates ───────────────────────
    { u: "Sulaibiya",                 v: "Abbasiya",                 weight: 8 },
    { u: "Amghara",                   v: "Sulaibiya",                weight: 9 },

    // ── Mubarak Al-Kabeer internal ───────────────────────
    { u: "Sabah Al-Salem",            v: "Abu Al-Hasaniya",          weight: 2 },
    { u: "Sabah Al-Salem",            v: "Qurain",                   weight: 2 },
    { u: "Sabah Al-Salem",            v: "Fnaitees",                 weight: 2 },
    { u: "Sabah Al-Salem",            v: "Qusour",                   weight: 2 },
    { u: "Abu Al-Hasaniya",           v: "Fnaitees",                 weight: 2 },
    { u: "Qurain",                    v: "Qusour",                   weight: 2 },
    { u: "Qurain",                    v: "Abu Fatira",               weight: 1 },
    { u: "Qusour",                    v: "Subhan",                   weight: 3 },
    { u: "Fnaitees",                  v: "Mseela",                   weight: 2 },
    { u: "Mseela",                    v: "Abu Fatira",               weight: 3 },
    { u: "Mseela",                    v: "Adan",                     weight: 3 },
    { u: "Adan",                      v: "Abu Fatira",               weight: 3 },
    { u: "Subhan",                    v: "Adan",                     weight: 4 },

    // ── Mubarak Al-Kabeer ↔ other governorates ────────────
    { u: "Abu Al-Hasaniya",           v: "Bayan",                    weight: 2 },
    { u: "Fnaitees",                  v: "Rumaithiya",               weight: 2 },
    { u: "Subhan",                    v: "Rehab",                    weight: 5 },
  ],
};

export function getNeighbors(
  nodeId: string,
  edges: EdgeDef[]
): Array<{ dest: string; weight: number }> {
  const result: Array<{ dest: string; weight: number }> = [];
  for (const e of edges) {
    if (e.u === nodeId) result.push({ dest: e.v, weight: e.weight });
    else if (e.v === nodeId) result.push({ dest: e.u, weight: e.weight });
  }
  return result;
}
